services:

  dispatcher:
    build: ./dispatcher
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://dispatcher-mongo:27017
    depends_on:
      - dispatcher-mongo
      - auth-service
      - course-service
      - exam-service
      - booking-service
    networks:
      - internal

  auth-service:
    build: ./auth_service
    expose:
      - "8001"
    environment:
      - MONGO_URL=mongodb://auth-mongo:27017
    depends_on:
      - auth-mongo
    networks:
      - internal

  course-service:
    build: ./course_service
    expose:
      - "8000"
    depends_on:
      - course-mongo
    networks:
      - internal

  exam-service:
    build: ./exam_service
    expose:
      - "8000"
    depends_on:
      - exam-mongo
    networks:
      - internal

  booking-service:
    build: ./booking_service
    expose:
      - "8000"
    environment:
      - MONGO_URL=mongodb://booking-mongo:27017
    depends_on:
      - booking-mongo
    networks:
      - internal

  dispatcher-mongo:
    image: mongo:7
    volumes:
      - dispatcher-mongo-data:/data/db
    networks:
      - internal

  auth-mongo:
    image: mongo:7
    volumes:
      - auth-mongo-data:/data/db
    networks:
      - internal

  course-mongo:
    image: mongo:7
    volumes:
      - course-mongo-data:/data/db
    networks:
      - internal

  exam-mongo:
    image: mongo:7
    volumes:
      - exam-mongo-data:/data/db
    networks:
      - internal

  booking-mongo:
    image: mongo:7
    volumes:
      - booking-mongo-data:/data/db
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - internal
  mongodb-exporter:
    image: percona/mongodb_exporter:0.40
    command:
      - '--mongodb.uri=mongodb://dispatcher-mongo:27017'
      - '--collect-all'
    networks:
      - internal
    expose:
      - "9216"
    depends_on:
      - dispatcher-mongo

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - internal
    depends_on:
      - prometheus

networks:
  internal:
    driver: bridge

volumes:
  dispatcher-mongo-data:
  auth-mongo-data:
  course-mongo-data:
  exam-mongo-data:
  booking-mongo-data:
  grafana-data: