version: "3.9"

services:

  dispatcher:
    build: ./dispatcher
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://dispatcher-mongo:27017
    depends_on:
      - dispatcher-mongo
      - auth-service
      - course-service
      - exam-service
    networks:
      - internal

  auth-service:
    build: ./auth_service
    expose:
      - "8001"
    environment:
      - MONGO_URL=mongodb://auth-mongo:27017
    depends_on:
      - auth-mongo
    networks:
      - internal

  course-service:
    build: ./course_service
    expose:
      - "8000"
    depends_on:
      - course-mongo
    networks:
      - internal

  exam-service:
    build: ./exam_service
    expose:
      - "8000"
    depends_on:
      - exam-mongo
    networks:
      - internal

  dispatcher-mongo:
    image: mongo:7
    volumes:
      - dispatcher-mongo-data:/data/db
    networks:
      - internal

  auth-mongo:
    image: mongo:7
    volumes:
      - auth-mongo-data:/data/db
    networks:
      - internal

  course-mongo:
    image: mongo:7
    volumes:
      - course-mongo-data:/data/db
    networks:
      - internal

  exam-mongo:
    image: mongo:7
    volumes:
      - exam-mongo-data:/data/db
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  dispatcher-mongo-data:
  auth-mongo-data:
  course-mongo-data:
  exam-mongo-data: